steps:
- id: 'Build Spring Boot App'
  name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
- id: 'Build Docker Image'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:1.0.$SHORT_SHA',
         '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:latest',
         '-f', 'Dockerfile',
         '.']
- id: 'Push the Docker Image to GCR'
  name: 'gcr.io/cloud-builders/docker'
  args: [ "push", "gcr.io/$PROJECT_ID/$REPO_NAME:1.0.$SHORT_SHA"]
- id: 'Update Image in GKE Deployment'
  name: 'gcr.io/cloud-builders/kubectl'
  args:
  - set
  - image
  - deployment
  - $REPO_NAME
  - $REPO_NAME=gcr.io/$PROJECT_ID/$REPO_NAME:1.0.$SHORT_SHA
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-east1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=spring-boot'

images:
- 'gcr.io/$PROJECT_ID/$REPO_NAME:latest'
